version: '3.8'

services:
  api:
    container_name: baldussi-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: baldussi-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "baldussi"
      POSTGRES_USER: "baldussi"
      POSTGRES_DB: "baldussi"

volumes:
  pgdata:
